# Generated by Django 6.1 on 2026-08-22 07:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('strapline', models.CharField(blank=True, max_length=30)),
                ('form', models.CharField(choices=[('soap', 'Soap'), ('oil', 'Oil'), ('powder', 'Powder'), ('capsule', 'Capsule'), ('tea', 'Tea'), ('cream', 'Cream'), ('liquid', 'Liquid'), ('other', 'Other')], max_length=20)),
                ('size_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('piece', 'piece')], max_length=10)),
                ('brief', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('supports', models.CharField(blank=True, max_length=200)),
                ('ingredients', models.TextField()),
                ('how_to_use', models.TextField()),
                ('precautions', models.TextField()),
                ('storage', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('method_note', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('price_kobo', models.PositiveIntegerField(help_text='Price in kobo (₦1 = 100 kobo)')),
                ('compare_at_price_kobo', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('nafdac_number', models.CharField(blank=True, max_length=40)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('search_terms', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.category')),
                ('concerns', models.ManyToManyField(blank=True, related_name='products', to='catalogue.concern')),
                ('related_products', models.ManyToManyField(blank=True, to='catalogue.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_published'], name='catalogue_p_categor_206924_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', '-created_at'], name='catalogue_p_is_publ_e0890b_idx'),
        ),
    ]
